import {
	AccuracyChallenge,
	AdaptiveSpeed,
	Alternate,
	ApproachDifferent,
	Autoplay,
	BarrelRoll,
	Blinds,
	Bloom,
	Bubbles,
	Classic,
	Daycore,
	Deflate,
	Depth,
	DifficultyAdjust,
	DoubleTime,
	DualStages,
	Easy,
	Flashlight,
	FreezeFrame,
	Grow,
	HalfTime,
	HardRock,
	Hidden,
	Magnetised,
	Mirror,
	MovingFast,
	Muted,
	Nightcore,
	NoFail,
	NoMod,
	NoScope,
	Perfect,
	Random,
	Relax,
	Repel,
	SimplifiedRhythm,
	SingleTap,
	SpinIn,
	SpunOut,
	StrictTracking,
	SuddenDeath,
	Synesthesia,
	TargetPractice,
	TouchDevice,
	Traceable,
	Transform,
	Wiggle,
	WindDown,
	WindUp,
} from "$lib";

export const ModType = {
	DIFF_INCREASE: "diff_increase",
	DIFF_DECREASE: "diff_decrease",
	AUTOMATION: "automation",
	FUN: "fun",
	SPECIAL: "special",
	UTIL: "util",
};

export const modTypeColors = {
	[ModType.DIFF_INCREASE]: "#FF6666",
	[ModType.DIFF_DECREASE]: "#B3FF66",
	[ModType.AUTOMATION]: "#66CCFF",
	[ModType.FUN]: "#FF66AB",
	[ModType.SPECIAL]: "#8C66FF",
	[ModType.UTIL]: "#FFCC22",
};

export const stableMods = {
	[ModType.UTIL]: [
		{ acronym: "NM", name: "No Mod", component: NoMod },
		{ acronym: "TD", name: "Touch Device", component: TouchDevice },
	],
	[ModType.DIFF_INCREASE]: [
		{ acronym: "DT", name: "Double Time", component: DoubleTime },
		{ acronym: "NC", name: "Nightcore", component: Nightcore },
		{ acronym: "HD", name: "Hidden", component: Hidden },
		{ acronym: "HR", name: "Hard Rock", component: HardRock },
		{ acronym: "FL", name: "Flashlight", component: Flashlight },
		{ acronym: "PF", name: "Perfect", component: Perfect },
		{ acronym: "SD", name: "Sudden Death", component: SuddenDeath },
	],

	[ModType.DIFF_DECREASE]: [
		{ acronym: "NF", name: "No Fail", component: NoFail },
		{ acronym: "EZ", name: "Easy", component: Easy },
		{ acronym: "HT", name: "Half Time", component: HalfTime },
		{ acronym: "SO", name: "Spun Out", component: SpunOut },
	],

	[ModType.AUTOMATION]: [
		{ acronym: "AT", name: "Autoplay", component: Autoplay },
		{ acronym: "RX", name: "Relax", component: Relax },
	],
};

export const lazerMods = {
	[ModType.DIFF_INCREASE]: [
		{ acronym: "AL", name: "Alternate", component: Alternate },
		{ acronym: "AC", name: "Accuracy Challenge", component: AccuracyChallenge },
		{ acronym: "AS", name: "Adaptive Speed", component: AdaptiveSpeed },
		{ acronym: "AD", name: "Approach Different", component: ApproachDifferent },
		{ acronym: "BL", name: "Blinds", component: Blinds },
		{ acronym: "MF", name: "Moving Fast", component: MovingFast },
		{ acronym: "NS", name: "No Scope", component: NoScope },
		{ acronym: "SG", name: "Single Tap", component: SingleTap },
		{ acronym: "ST", name: "Strict Tracking", component: StrictTracking },
		{ acronym: "WU", name: "Wind Up", component: WindUp },
	],

	[ModType.DIFF_DECREASE]: [
		{ acronym: "DC", name: "Daycore", component: Daycore },
		{ acronym: "DF", name: "Deflate", component: Deflate },
		{ acronym: "WD", name: "Wind Down", component: WindDown },
	],

	[ModType.FUN]: [
		{ acronym: "BR", name: "Barrel Roll", component: BarrelRoll },
		{ acronym: "BM", name: "Bloom", component: Bloom },
		{ acronym: "BB", name: "Bubbles", component: Bubbles },
		{ acronym: "DP", name: "Depth", component: Depth },
		{ acronym: "DS", name: "Dual Stages", component: DualStages },
		{ acronym: "FF", name: "Freeze Frame", component: FreezeFrame },
		{ acronym: "GR", name: "Grow", component: Grow },
		{ acronym: "MG", name: "Magnetised", component: Magnetised },
		{ acronym: "MR", name: "Mirror", component: Mirror },
		{ acronym: "MU", name: "Muted", component: Muted },
		{ acronym: "RD", name: "Random", component: Random },
		{ acronym: "RP", name: "Repel", component: Repel },
		{ acronym: "SR", name: "Simplified Rhythm", component: SimplifiedRhythm },
		{ acronym: "SI", name: "Spin In", component: SpinIn },
		{ acronym: "SY", name: "Synesthesia", component: Synesthesia },
		{ acronym: "TC", name: "Traceable", component: Traceable },
		{ acronym: "WG", name: "Wiggle", component: Wiggle },
	],

	[ModType.SPECIAL]: [
		{ acronym: "CL", name: "Classic", component: Classic },
		{ acronym: "DA", name: "Difficulty Adjust", component: DifficultyAdjust },
		{ acronym: "TP", name: "Target Practice", component: TargetPractice },
		{ acronym: "TR", name: "Transform", component: Transform },
	],
};
